/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eancode;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import eancode.Docmissing;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author santosh
 */
public class testjdsearch extends javax.swing.JDialog {

    /**
     * Creates new form testjd
     */
    DbConnection dbconn = new DbConnection(); 
    GlobalVariable gv = new GlobalVariable();
    Connection scanconnekt = null;
    Statement scanstmt = null;
    PreparedStatement scanpst =null;
    ResultSet scanrs = null;
    public String updateto = "";
    
    public testjdsearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            scanconnekt =  dbconn.conn();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(testjdsearch.class.getName()).log(Level.SEVERE, null, ex);
        }
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctypset = new javax.swing.JLabel();
        docnumset = new javax.swing.JLabel();
        jcomobostat = new javax.swing.JComboBox();
        save = new javax.swing.JButton();

        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        doctypset.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        doctypset.setText("jLabel1");

        docnumset.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        docnumset.setText("jLabel2");

        jcomobostat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jcomobostat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "test", "test1" }));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(doctypset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(docnumset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcomobostat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(save)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctypset)
                    .addComponent(docnumset)
                    .addComponent(jcomobostat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            // TODO add your handling code here:
            if(updateto.equals("doctypetbl"))
            {
            updatetbl();
            }
            else if(updateto.equals("grntbl"))
            {
                updategrntbl();
            }
            System.out.println("this is test");
        this.setVisible(false);
       
          
        } catch (Exception ex) {
            Logger.getLogger(testjdsearch.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
            
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        
        Docmissing.jButton1.doClick();    
        
    }//GEN-LAST:event_formWindowLostFocus

public void updategrntbl() throws Exception
  {        
  String grnstatus = jcomobostat.getSelectedItem().toString().trim();    
  String updategrnstr ="UPDATE grnseriestbl SET grnstatus = '" + grnstatus + "'  WHERE doctype = '" + doctypset.getText() + "' and grnserlnum = '" + docnumset.getText().substring(5, 9) + "'"; ; 
  System.out.println(updategrnstr);
  scanpst = scanconnekt.prepareStatement(updategrnstr);
  scanpst.executeUpdate();    
  }
         

public void updatetbl() throws Exception
 {
      
 String selectstatus = jcomobostat.getSelectedItem().toString().trim();    
 String updatedocstr ="UPDATE doctyperegistertbl SET docstatus = '" + selectstatus + "'  WHERE doctype = '" + doctypset.getText() + "' and docnum = '" + docnumset.getText() + "'"; ; 
 System.out.println(updatedocstr);
 scanpst = scanconnekt.prepareStatement(updatedocstr);
 scanpst.executeUpdate(); 
 
 }


/**
* @param args the command line arguments
*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testjdsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testjdsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testjdsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testjdsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                testjdsearch dialog = new testjdsearch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel docnumset;
    public javax.swing.JLabel doctypset;
    public javax.swing.JComboBox jcomobostat;
    public javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
